#version 450

layout(binding = 0) buffer b0 {
   float a[];
};

layout(binding = 1) buffer b1 {
   float b[];
};

layout(binding = 2) buffer b2 {
   float c[];
};

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void sum() 
{
    uint i = gl_GlobalInvocationID.x;
    c[i] = a[i] + b[i];
}

void mul() 
{
    uint i = gl_GlobalInvocationID.x;
    c[i] = a[i] * b[i];
}

void power() 
{
    uint i = gl_GlobalInvocationID.x;
    c[i] = pow(2., a[i]);
}
